# !/usr/bin/env/python
# _*_coding:utf-8 _*_
# author:LiangJianfei

from bs4 import BeautifulSoup
from fake_useragent import UserAgent
from Random_UA import Ran
import requests

start_url = "https://bj.58.com/sale.shtml"
url_host = "https://bj.58.com"
# headers = {"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1944.0 Safari/537.36"}
def get_channel_urls(url):
    headers = Ran().random_useragent()
    wb_data = requests.get(url,headers=headers)
    soup = BeautifulSoup(wb_data.text,'lxml')
    links = soup.select('ul.ym-submnu > li > span > a')
    channel_urls = ''
    for link in links:
        page_url = url_host + link.get("href")
        channel_urls += page_url
        channel_urls += "\n"
    return channel_urls

# channel_list = get_channel_urls(start_url)

channel_list = '''
https://bj.58.com/iphonesj/
https://bj.58.com/sanxing/
https://bj.58.com/xiaomi/
https://bj.58.com/huaweisj/
https://bj.58.com/oppo/
https://bj.58.com/vivo/
https://bj.58.com/meizu/
https://bj.58.com/kupaisj/
https://bj.58.com/lianxiang/
https://bj.58.com/zhongxingshouji/
https://bj.58.com/motuoluola/
https://bj.58.com/nuojiya/
https://bj.58.com/ailixin/
https://bj.58.com/heimei/
https://bj.58.com/shoujiyewu/
https://bj.58.com/chonzhika/
https://bj.58.com/xiaolingtong/
https://bj.58.com/yamaha/
https://bj.58.com/bentianmoto/
https://bj.58.com/jialing/
https://bj.58.com/lingmumoto/
https://bj.58.com/zongshen/
https://bj.58.com/qingqi/
https://bj.58.com/wanliang/
https://bj.58.com/tabanmotuoche/
https://bj.58.com/qishiche/
https://bj.58.com/gonglusai/
https://bj.58.com/miniche/
https://bj.58.com/dapailiang/
https://bj.58.com/aima/
https://bj.58.com/xiaoniao/
https://bj.58.com/qingqiddc/
https://bj.58.com/lvyuanddc/
https://bj.58.com/xinri/
https://bj.58.com/diandongzixingche/
https://bj.58.com/diandongmotuoche/
https://bj.58.com/zhediediandongche/
https://bj.58.com/zhudongche/
https://bj.58.com/laoniandaibuche/
https://bj.58.com/jieante/
https://bj.58.com/meilida/
https://bj.58.com/yongjiu/
https://bj.58.com/fenghuangzxc/
https://bj.58.com/feige/
https://bj.58.com/jiema/
https://bj.58.com/putongzixingche/
https://bj.58.com/shandizixingche/
https://bj.58.com/gongluzixingche/
https://bj.58.com/zhediezixingche/
https://bj.58.com/minizixingche/
https://bj.58.com/jiaotasanlunche/
https://bj.58.com/diandongsanlunche/
https://bj.58.com/zhulisanlunche/
https://bj.58.com/zixingchepeijian/
https://bj.58.com/diandongchekongpeijian/
https://bj.58.com/diandongchedianchi/
https://bj.58.com/xiuchegongju/
https://bj.58.com/qixingzhuangbei/
https://bj.58.com/taishiji/
https://bj.58.com/fuwuqi/
https://bj.58.com/ibm/
https://bj.58.com/lenovo/
https://bj.58.com/apple/
https://bj.58.com/dell/
https://bj.58.com/asus/
https://bj.58.com/compaq/
https://bj.58.com/sony/
https://bj.58.com/samsung/
https://bj.58.com/pbdnipad/
https://bj.58.com/pbdnsanxing/
https://bj.58.com/pbdnlianxiang/
https://bj.58.com/pbdnaiguozhe/
https://bj.58.com/wangka/
https://bj.58.com/xianshiqi/
https://bj.58.com/cpu/
https://bj.58.com/xianka/
https://bj.58.com/zhuban/
https://bj.58.com/yingpan/
https://bj.58.com/ydyingpan/
https://bj.58.com/zhoubianshebei/pve_5620_398628/
https://bj.58.com/bujianduandianyuan/
https://bj.58.com/shubiao/
https://bj.58.com/shexiangtou/
https://bj.58.com/usb/
https://bj.58.com/smqita/pve_5623_398637/
https://bj.58.com/smqita/pve_5623_398636/
https://bj.58.com/smqita/
https://bj.58.com/danfanxiangji/
https://bj.58.com/kapianxiangji/
https://bj.58.com/weidanxiangji/
https://bj.58.com/jingtou/
https://bj.58.com/xiangjipeijian/
https://bj.58.com/qitaxiangji/
https://bj.58.com/ipod/
https://bj.58.com/mpsantouch/
https://bj.58.com/mpsannano/
https://bj.58.com/mpsan/
https://bj.58.com/mpsi/
https://bj.58.com/psp/
https://bj.58.com/yxjpsv/
https://bj.58.com/yxjnds/
https://bj.58.com/yxjxbox/
https://bj.58.com/yxjpssan/
https://bj.58.com/yxjpser/
https://bj.58.com/yxjwii/
https://bj.58.com/biguakt/
https://bj.58.com/guishikt/
https://bj.58.com/zhongyangkt/
https://bj.58.com/yjcaidian/
https://bj.58.com/gqcaidian/
https://bj.58.com/dlzcaidian/
https://bj.58.com/quanzidongxiyiji/
https://bj.58.com/guntongxiyiji/
https://bj.58.com/shuanggangxiyiji/
https://bj.58.com/minixiyiji/
https://bj.58.com/shuangkaimenbx/
https://bj.58.com/duikaimenbx/
https://bj.58.com/minibx/
https://bj.58.com/yingyinjiadian/
https://bj.58.com/shenghuojiadian/
https://bj.58.com/chuweijiadian/
https://bj.58.com/jiadianpeijian/
https://bj.58.com/lishibg/
https://bj.58.com/wohibg/
https://bj.58.com/zhanshibg/
https://bj.58.com/danrenchuang/
https://bj.58.com/shuanrenchuang/
https://bj.58.com/chuangcengchuang/
https://bj.58.com/zhediechuang/
https://bj.58.com/tongchuang/
https://bj.58.com/chuangdian/
https://bj.58.com/guizi/
https://bj.58.com/zhuolei/
https://bj.58.com/zuoju/
https://bj.58.com/jiajushafa/
https://bj.58.com/chaji/
https://bj.58.com/jujia/
https://bj.58.com/muyingzaojiao/
https://bj.58.com/weiyangfushi/
https://bj.58.com/ertongyongpin/
https://bj.58.com/weiyangyingyangpin/
https://bj.58.com/zhiniaoku/
https://bj.58.com/weiyangnaiping/
https://bj.58.com/yongpinlalaku/
https://bj.58.com/yongpinbeidai/
https://bj.58.com/weiyangnaizui/
https://bj.58.com/yongpinxuebudai/
https://bj.58.com/weiyangxinaiqi/
https://bj.58.com/yongpinyouxidai/
https://bj.58.com/weiyangnuannaiqi/
https://bj.58.com/yongpinjianshenjia/
https://bj.58.com/yingerchuang/
https://bj.58.com/yongpinshuidai/
https://bj.58.com/naifen/
https://bj.58.com/yingerche/
https://bj.58.com/tongchexuebu/
https://bj.58.com/tongcheyaoyi/
https://bj.58.com/tongzuoyi/
https://bj.58.com/tongcanyi/
https://bj.58.com/tongniuche/
https://bj.58.com/tongzixingche/
https://bj.58.com/tongsanlunche/
https://bj.58.com/yongpintaixin/
https://bj.58.com/fangfusefu/
https://bj.58.com/mmfuzhuang/
https://bj.58.com/yongpinshoufu/
https://bj.58.com/yongpinyunfuzhen/
https://bj.58.com/fushipeijian/
https://bj.58.com/fuzhuangshoushi/
https://bj.58.com/fuzhuangshoubiao/
https://bj.58.com/fuzhuangtxue/
https://bj.58.com/fuzhuangchenshan/
https://bj.58.com/fuzhuangwaitao/
https://bj.58.com/meirongyongpin/
https://bj.58.com/hufu/
https://bj.58.com/meirongmeiti/
https://bj.58.com/fuzhuangkuzi/
https://bj.58.com/caizhuang/
https://bj.58.com/baojianshipin/
https://bj.58.com/meifa/
https://bj.58.com/xiangshuimr/
https://bj.58.com/gudongguwan/
https://bj.58.com/mingxingwupin/
https://bj.58.com/shufa/
https://bj.58.com/shanshuihua/
https://bj.58.com/qunzifs/
https://bj.58.com/fuzhuangxizhuang/
https://bj.58.com/tongzhuang/
https://bj.58.com/xiuxianxie/
https://bj.58.com/yundongxie/
https://bj.58.com/fanbuxie/
https://bj.58.com/gaogenxie/
https://bj.58.com/xiebanxi/
https://bj.58.com/pixie/
https://bj.58.com/xiangbaodanjian/
https://bj.58.com/xiangbaoshuangjian/
https://bj.58.com/xiangbaoshubao/
https://bj.58.com/xiangbaoqianbao/
https://bj.58.com/xiangbaolagan/
https://bj.58.com/xiangbaodiannao/
https://bj.58.com/renwuhua/
https://bj.58.com/huaniaohua/
https://bj.58.com/zhuangshihua/
https://bj.58.com/guijinshu/
https://bj.58.com/zhubaoshshi/
https://bj.58.com/fangjinshshi/
https://bj.58.com/zhubaoshipin/pve_5731_398646/
https://bj.58.com/zhubaoshipin/pve_5731_398647/
https://bj.58.com/youpiaoyoupin/
https://bj.58.com/fanggujiaju/
https://bj.58.com/aoyunjinianbi/
https://bj.58.com/sbjinianpin/
https://bj.58.com/cddvd/
https://bj.58.com/yingpandianshiju/
https://bj.58.com/ruanjiants/
https://bj.58.com/jishulei/
https://bj.58.com/gongjushu/
https://bj.58.com/kaoshi/
https://bj.58.com/shenghuolei/
https://bj.58.com/xiaoshuo/
https://bj.58.com/youyongwt/
https://bj.58.com/yujiawt/
https://bj.58.com/diaoyuyongju/
https://bj.58.com/qipai/
https://bj.58.com/yundongfushi/pve_5728_398644/
https://bj.58.com/yundongfushi/pve_5728_398648/
https://bj.58.com/tabuji/
https://bj.58.com/peobuji/
https://bj.58.com/anmoyi/
https://bj.58.com/liubinghuaban/
https://bj.58.com/jianshenche/
https://bj.58.com/xueshwenju/
https://bj.58.com/jiaoxueyj/
https://bj.58.com/taiqiuzhuo/
https://bj.58.com/wangqiuyongpin/
https://bj.58.com/zuqiuwt/
https://bj.58.com/pingpangqiuwt/
https://bj.58.com/yumaoqiuwt/
https://bj.58.com/lanqiutw/
https://bj.58.com/jiayouka/
https://bj.58.com/jita/
https://bj.58.com/xiyuka/
https://bj.58.com/gangqin/
https://bj.58.com/zhaojiaoka/
https://bj.58.com/dianziqin/
https://bj.58.com/tushuka/
https://bj.58.com/shoufengqing/
https://bj.58.com/xiaofeika/
https://bj.58.com/kqqita/
https://bj.58.com/saomiaoyi/
https://bj.58.com/yitiji/
https://bj.58.com/chuanzhenji/
https://bj.58.com/erhuwt/
https://bj.58.com/touyingji/
https://bj.58.com/chongzhika/
https://bj.58.com/yitiji/
https://bj.58.com/fuyinji/
https://bj.58.com/dayinji/
https://bj.58.com/tanfen/
https://bj.58.com/mohemoshui/
https://bj.58.com/wanggouka/
https://bj.58.com/wenjiangui/
https://bj.58.com/huiyizhuo/
https://bj.58.com/baoxiangui/
https://bj.58.com/bangongzhuoyi/
https://bj.58.com/bangongyi/
https://bj.58.com/bangongjiaju/pve_5733_398638/
https://bj.58.com/bangongjiaju/pve_5733_398639/
https://bj.58.com/jianshenka/
https://bj.58.com/gongjiaoka/
https://bj.58.com/dangaoka/
https://bj.58.com/xicheka/
https://bj.58.com/youyongka/
https://bj.58.com/huagong/
https://bj.58.com/fangzhi/
https://bj.58.com/fyinshua/
https://bj.58.com/gongcheng/
https://bj.58.com/zaozhi/
https://bj.58.com/kuangye/
https://bj.58.com/mugongshebei/
https://bj.58.com/diandongji/
https://bj.58.com/nongye/
https://bj.58.com/yintundaomo/
https://bj.58.com/xingwanou/
https://bj.58.com/jiandanbianxie/
https://bj.58.com/nanyongchuandai/
https://bj.58.com/fangzhenrufang/
https://bj.58.com/zhendongbang/
https://bj.58.com/yindiciji/
https://bj.58.com/gdianhouting/
https://bj.58.com/tiaodan/
https://bj.58.com/lingleiwanju/
https://bj.58.com/fengrutiaodou/
https://bj.58.com/yanshitaohuan/
https://bj.58.com/tiaoqingxiangshui/
https://bj.58.com/jiqingyongju/
https://bj.58.com/zhifuyouhuo/
https://bj.58.com/qingqutiaosao/
https://bj.58.com/dingziku/
https://bj.58.com/siwameitui/
https://bj.58.com/nanshineiyi/
https://bj.58.com/runhuaji/
https://bj.58.com/aqyp/
https://bj.58.com/anquantao/
https://bj.58.com/qitachengren/
https://bj.58.com/xiaoyuan/pve_5536_1/
https://bj.58.com/xiaoyuan/pve_5536_2/
https://bj.58.com/xiaoyuan/pve_5536_3/
https://bj.58.com/xiaoyuan/pve_5536_4/
https://bj.58.com/xiaoyuan/pve_5536_5/
https://bj.58.com/esqgjiaju/
https://bj.58.com/esqgfuzhuang/
https://bj.58.com/esqgtushu/
https://bj.58.com/ershouqiugou/
https://bj.58.com/wangyou/
https://bj.58.com/huanwu/
https://bj.58.com/lipin/
https://bj.58.com/wuyuanwupin/
https://bj.58.com/fuwujy/
https://bj.58.com/canjirenyongpin/
https://bj.58.com/weixing/
https://bj.58.com/qitatiaozao/
'''